[workspace]
resolver = "2"

default-members = [
    "lib",
    "ztest",
]

members = [
    "lib",
    "ztest",
    "examples/solo",
    "examples/duo",
    "examples/duo-unit",
    "examples/helios-dev",
]

[workspace.dependencies]
thiserror = "1.0"
anyhow = "1.0"
zone = "0.1.8"
regex = "1.5"
smf = "0.2"
libnet = { git = "https://github.com/oxidecomputer/netadm-sys", branch = "main" }
fs2 = { git = "https://github.com/pfmooney/fs2-rs", branch = "illumos-target" }
uuid = { version = "1.0.0", features = [ "serde", "v4" ] }
serde = "1.0"
ron = "0.7"
slog = "2.7"
slog-term = "2.7"
slog-async = "2.7"
slog-envlogger = "2.2"
home = "0.5"
propolis-client = { git = "https://github.com/oxidecomputer/propolis", branch = "master" }
propolis-server-config = { git = "https://github.com/oxidecomputer/propolis", branch = "master" }
toml = "0.7"
libc = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.14"
futures = "0.3"
clap = { version = "4.0.28", features = ["color", "derive"] }
tabwriter = { version = "1", features = ["ansi_formatting"] }
colored = "2"
rand = "0.8"
portpicker = "0.1"
camino = { version = "1.1.1", features = ["serde1"] }
reqwest = "0.11.22"
