[env]
LIBZFS_CORE_LOOKUP_WITH = "link"
# https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[net]
git-fetch-with-cli = true

# Set up pfexec as a target runner since tests always need to be run as root.
[target.'cfg(target_os = "illumos")']
runner = "pfexec"
