[package]
name = "ztest"
version = "0.1.0"
edition = "2021"

[dependencies]
zone = { git = "https://github.com/oxidecomputer/zone" }

libnet.workspace = true
anyhow.workspace = true
tokio.workspace = true
oxnet.workspace = true
